name: Grass Is Greener

#on:
#  schedule:
#    - cron : "40 06 * * *"
  
jobs:
  update_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get date
        run: |
          date > ./data.md
          ls
      - uses: stefanzweifel/git-auto-commit-action@v4
